### ISSUE TITLE
Patcher for Steam History Edition?

### ISSUE THREAD

**Issue by hikarosato** [Eisenmonoxid/S6Patcher#1]
Will it be possible in the future that we get support for Steam History Edition?

**Comment by hikarosato** [comment]
I just watched new commits, and I'm happy! I wish you good luck with easily integration for Steam HE version!

**Comment by Eisenmonoxid** [comment]
Hey,
Steam HE integration is already done, however i am still working on another feature for the mapeditor and i need to do some testing before i can push a new release. 

If you want to patch your Steam HE now, you can take the latest commit on the master branch and compile that. It should work without problems. Like the OV from Steam, the HE will also need to be extracted with Steamless first.
